In [4]:
from pybaseball import statcast
import pandas as pd

In [5]:
data = statcast(start_dt='2018-03-29', end_dt='2018-04-30')
data.head(5)

This is a large query, it may take a moment to complete
Completed sub-query from 2018-03-29 to 2018-04-03
Completed sub-query from 2018-04-04 to 2018-04-09
Completed sub-query from 2018-04-10 to 2018-04-15
Completed sub-query from 2018-04-16 to 2018-04-21
Completed sub-query from 2018-04-22 to 2018-04-27
Completed sub-query from 2018-04-28 to 2018-04-30

,index,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,...,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment
0,73,FF,2018-04-30,95.9,-0.9267,6.0290,Roberto Osuna,543257.0,532077.0,field_out,...,5.0,7.0,5.0,7.0,7.0,5.0,5.0,7.0,Standard,Standard
1,76,FC,2018-04-30,91.9,-0.8903,6.0548,Roberto Osuna,543257.0,532077.0,NaN,...,5.0,7.0,5.0,7.0,7.0,5.0,5.0,7.0,Standard,Standard
2,84,FC,2018-04-30,92.5,-0.9000,6.0163,Roberto Osuna,543257.0,532077.0,NaN,...,5.0,7.0,5.0,7.0,7.0,5.0,5.0,7.0,Standard,Standard
3,86,FF,2018-04-30,95.1,-0.7952,6.0494,Roberto Osuna,596146.0,532077.0,double,...,5.0,7.0,5.0,7.0,7.0,5.0,5.0,7.0,Standard,Standard
4,94,FF,2018-04-30,94.8,-0.8955,5.9308,Roberto Osuna,596146.0,532077.0,NaN,...,5.0,7.0,5.0,7.0,7.0,5.0,5.0,7.0,Standard,Standard